# Generated by Django 6.0.1 on 2026-01-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('przedmioty', models.ManyToManyField(to='korepetycje.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('przedmioty', models.ManyToManyField(to='korepetycje.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odbywania', models.DateTimeField()),
                ('status', models.CharField(choices=[('PL', 'Planowana'), ('ODB', 'Odbyta'), ('ODW', 'Odwołana')], default='PL', max_length=3)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korepetycje.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korepetycje.uczen')),
            ],
        ),
    ]
