# Generated by Django 6.0.1 on 2026-01-28 18:54

import django.db.models.deletion
import korepetycje.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('wlasciciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('przedmioty', models.ManyToManyField(to='korepetycje.przedmiot')),
            ],
            options={
                'verbose_name': 'Nauczyciel',
                'verbose_name_plural': 'Nauczyciele',
                'permissions': [('can_view_other_owners', 'Może widzieć nauczycieli innych użytkowników')],
            },
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu', models.CharField(max_length=20)),
                ('przedmioty', models.ManyToManyField(to='korepetycje.przedmiot')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczeń',
                'verbose_name_plural': 'Uczniowie',
            },
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(help_text='Ocena od 1 do 5', validators=[korepetycje.models.walidacja_oceny])),
                ('komentarz', models.TextField()),
                ('data_wystawienia', models.DateTimeField(auto_now_add=True)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='korepetycje.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korepetycje.uczen')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
            },
        ),
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odbywania', models.DateTimeField(validators=[korepetycje.models.walidacja_daty_przyszlej])),
                ('status', models.CharField(choices=[('PL', 'Planowana'), ('ODB', 'Odbyta'), ('ODW', 'Odwołana')], default='PL', max_length=3)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korepetycje.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korepetycje.uczen')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
                'ordering': ['data_odbywania'],
            },
        ),
    ]
