# Generated by Django 6.0.1 on 2026-01-26 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekcja',
            options={'verbose_name': 'Lekcja', 'verbose_name_plural': 'Lekcje'},
        ),
        migrations.AddField(
            model_name='nauczyciel',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
