# Generated by Django 6.0.1 on 2026-01-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nauczyciel',
            options={'verbose_name': 'Nauczyciel', 'verbose_name_plural': 'Nauczyciele'},
        ),
        migrations.AlterModelOptions(
            name='przedmiot',
            options={'verbose_name': 'Przedmiot', 'verbose_name_plural': 'Przedmioty'},
        ),
        migrations.RemoveField(
            model_name='uczen',
            name='przedmioty',
        ),
    ]
