# Generated by Django 6.0.1 on 2026-01-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0002_alter_lekcja_options_nauczyciel_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nauczyciel',
            options={'permissions': [('can_view_other_owners', 'Może widzieć nauczycieli innych użytkowników')]},
        ),
    ]
