# Generated by Django 5.2.8 on 2025-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, default='2025-11-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[(1, 'Kobiea'), (2, 'Mezczyzna'), (3, 'Inna')], default=3),
        ),
    ]
